### PR TITLE
Fix e_value error with dates

### PR DESCRIPTION
**Pull request by odinuv**
Fix for issue #46. The issue raises when dates without time portion are supplied

### CODE REVIEW

**Comment by akejariwal** [comment]
@odinuv Does the change (POSIXlt -> POSIXct) work well with plotting? Did you test it?

CC @owenvallis @jnatanh

**Comment by owenvallis** [comment]
I just merged in his changes into my local repo and ran all the tests. The
package ran fine, and all of the plots look great. Looking at the code, it
seems all good to go.

On Tue, Aug 4, 2015 at 6:28 AM, Arun Kejariwal <notifications@github.com>
wrote:

> @odinuv <https://github.com/odinuv> Does the change (POSIXlt -> POSIXct)
> work well with plotting? Did you test it?
>
> CC @owenvallis <https://github.com/owenvallis> @jnatanh
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/AnomalyDetection/pull/53#issuecomment-127410385>
> .
>



-- 
Owen Vallis, Ph.D.
Professor of Music Technology: Intelligence, Interaction, and Design (MTIID)
California Institute of the Arts
http://www.flipmu.com

**Comment by akejariwal** [comment]
@caniszczyk  I approve the PR. Please merge.

**Comment by jhochenbaum** [comment]
@akejariwal seems like we still need to et this merged in

**Comment by akejariwal** [comment]
@caniszczyk Please merge this PR.

**Comment by dougmitarotonda** [comment]
Is there any update on when this will be merged?

**Pull request closed without merging**
