### PR TITLE
Issue 20: Issues using daily data with the "long_term" option

### PR DESCRIPTION
**Pull request by cozos**
1. Added a parameter(piecewise_median_period_weeks) that specifies the piecewise median time windows which was previously defaulted to 2 weeks.
2. Added an error message if max_outliers = 0 in a time window, prompting the user to choose a higher piecewise_median_period_weeks.
3. Made the time period passed to detect_anoms 2 x num_obs_per_period + 1 instead of 2 x num_obs_per_period.

### CODE REVIEW

**Comment by jhochenbaum** [comment]
Thanks a lot @cozos -- sounds good, I'm going to do a review shortly.

Best,

**Comment by owenvallis** [comment]
Hi @cozos, thanks again for the changes. The code looks solid except for an extra parenthesis on line 43 in detect_anoms.R. Once you remove it we can merge in the changes.

Best,

**Comment by akejariwal** [comment]
@cozos The Traviz CI build failed. Please have a look at the Details and submit a new PR.

cc @owenvallis @jhochenbaum

**Comment by cozos** [comment]
Hey, sorry for the sloppiness! I had neglected to check my notifications

**Pull request merged**
