### PR TITLE
fixed bug and added error handling when there are NAs in timestamp

### PR DESCRIPTION
**Pull request by terrytangyuan**
Currently, if there's NA in timestamp, R will give the following error:

```
Error in if (gran >= 86400) { : missing value where TRUE/FALSE needed
```

However, it is too hard for the user to know what the problem is, at least for me, I don't know where to fix the problem. I think this error handling is needed so that user knows where to go from here.

### CODE REVIEW

**Comment by terrytangyuan** [comment]
See this issue #28  I didn't notice someone else had this issue. It took the users a while to figure out the problem. They'll have to dig into the code to see how to fix it.

**Comment by akejariwal** [comment]
@caniszczyk I approve this PR. Please merge.

**Comment by terrytangyuan** [comment]
Could you merge this as well? Thanks.

**Comment by terrytangyuan** [comment]
Thanks Chris.

**Pull request merged**
